# Generated by Django 3.1.3 on 2022-03-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220318_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproduct',
            name='measureunit',
        ),
        migrations.RemoveField(
            model_name='historicalcategoryproduct',
            name='measureunit',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='category_product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoryproduct', verbose_name='Categoria de producto'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='measureunit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.measureunit', verbose_name='Unidad de medida'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='Categoria de producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='measureunit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='Unidad de medida'),
            preserve_default=False,
        ),
    ]
